#!/bin/bash
shopt -s extglob

function error_exit
{
    echo "$1" 1>&2
    exit 1
}


# Check if commit message argument
if [ -z "$1" ]
then
    echo "deploy script error: What changes did you make? Type a commit message."
    exit 1
fi

#Build successfuly or exit
stack clean
stack build || error\_exit "deploy script error: Build failed"

#Push changes on develop branch to github
git add -A
git commit -m "$1" || error\_exit "deploy script error: No changes to commit"
git push -u origin develop

# Temporarily store uncommited changes
git stash

# Verify correct branch
git checkout develop

# Build new files
stack exec website clean
stack exec website build

# Get previous files
git fetch --all
git checkout -b master --track origin/master

# Overwrite existing files with new files
rsync -a --filter='P _site/'      \
         --filter='P _cache/'     \
         --filter='P .git/'       \
         --filter='P .gitignore'  \
         --filter='P README.md'   \
         --filter='P .stack-work' \
         --delete-excluded        \
         _site/ .

# Commit
git add -A
git commit -m "Publish."

# Push
git push origin master:master

# Restoration
git checkout develop
git branch -D master
git stash pop
